config/routes.rb
Rails.application.routes.draw do
	root   'static_pages#home'
	get    '/share',   to: 'static_pages#share'
	get    '/information', to: 'static_pages#information'
	get    '/bio',   to: 'static_pages#bio'
	get    '/giving', to: 'static_pages#giving'
	get    '/signup',  to: 'users#new'
	post   '/signup',  to: 'users#create'
	get    '/login',   to: 'sessions#new'
	post   '/login',   to: 'sessions#create'
	delete '/logout',  to: 'sessions#destroy'
	resources :users do
	    member do
	    	get :following, :followers
	    end
	end
	resources :microposts,          only: [:create, :destroy]
	resources :foods,          only: [:create, :destroy]
	resources :relationships,       only: [:create, :destroy]
	# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
	def home
		if logged_in?
			@micropost  = current_user.microposts.build
			@food = current_user.foods.build
			@feed_items = current_user.feed.paginate(page: params[:page])
			@gift_items = current_user.food_feed.paginate(page: params[:page])
		end
	end

	def share
		if logged_in?
			@micropost  = current_user.microposts.build
		else
			flash[:danger] = "You must be signed up and logged in to make posts!"
		end
		@feed_items = Micropost.order(:id).paginate(page: params[:page])
	end

	def information
	end

	def bio
	end

	def giving
		if logged_in?
			@food  = current_user.foods.build
			@micropost  = current_user.microposts.build
		else
			flash[:danger] = "You must be signed up and logged in to post what you're bringing!"
		end
		@gift_items = Food.order(:id).paginate(page: params[:page])
	end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/bio.html.erb
<% provide(:title, "Biography") %>
<div class="container stuff">
<div class="bio jumbotron p-3 p-md-5 text-white rounded bg-dark">
	<div class="bio-pic img-thumbnail">
		<%= image_tag("Headshot.jpg", :size => 350, :alt => "Roger Michael") %>
	</div>

	<h1>Roger Mark Michael</h1>

	<p><strong>ROGER MARK MICHAEL</strong>, 63, departed this life for the next on January 5, 2019.  Born on July 1, 1955, in Clarksburg WV to Ernest and Martha Michael, and he was a graduate of South Harrison High School.  Roger resided in Fort Wayne IN with his wife of 25 years.</p>

	<p>Roger is survived by his wife Dacia, his three sons, Jeremy Michael (Amber), Dakota Michael and Dawson Michael (Jessica), and his three grandchildren Joshua, Lauri Ann and Rylie Marcella.  He is also survived by two sisters, and two brothers, Frankie Kelley (Layton), Connie Reynolds (Ken), Jeff Michael, Tim Michael (Raelynn), as well as twelve nieces and nephews.  Roger was preceded by both his parents, and his brother Lynn Michael.</p>

	<div class="bio-pic-right img-thumbnail">
		<%= image_tag("family.jpg", :size => 350, :alt => "Roger Michael") %>
	</div>

	<p>There was nothing more important to Roger than family. There was nothing Roger would not do for family.  And, there was nothing Roger lived for more than family.  He was flawed and broken, and yet strong, resilient, and a fierce defender of family, friends and the less fortunate.  While there were those who feared him, Roger was truly a gentle soul whose fierceness arose from his incredible drive to fight and stand for the justice of others.</p>

	<p>When it came to responsibility, Roger never shied away no matter the cost to self.  He was a tireless worker, and laser focused once a project began.  Roger was a simple man who desired little other than family and traveling with his family as often as possible.  He adored his children and grandchildren.  Little Lauri Ann called him Papaw and bossed him around as they worked on cars, watered the plants, took long walks, painted rocks and found ways to play in water both indoors and out.</p>

	<div class="bio-pic img-thumbnail">
		<%= image_tag("wedding.jpg", :size => 350, :alt => "Roger Michael") %>
	</div>

	<p>Roger considered eating an inconvenient necessity but he did like steak and potatoes, pepperoni pizza, cookies, donuts, apple pie, coffee at all hours of the day, regular Coke and the other food group BREAD!  He was quiet but quick witted, he managed to win way too many of the games we played, and he loved nothing more than a good slapstick prank and joking around.  Firecrackers and cold water were often involved.</p>

	<p>Roger loved his home state West Virginia for its mountains and call to a simpler life, but left it all behind to be with his immediate family in the flatlands of Indiana.  If he could have convinced us, he would have sold the house to travel across the United States in an RV.  There were so many places he still longed to see and so many family visits to attend.</p>

	<div class="bio-pic-right img-thumbnail">
		<%= image_tag("boat.jpg", :size => 350, :alt => "Roger Michael") %>
	</div>

	<p>Roger came into this world with so little.  He rose above and let go of so many challenges in life without letting it cause him to be bitter and hard although many saw him as hard.  He expected so little in regards to materials things, and yet hated that he did not have more to leave to his family.  Roger did not always fully understand that he was fearfully and wonderfully made in the image of God just as God had planned.  The legacy he left far outweighs any significance of tangible or material things.  Roger was divinely and uniquely what we needed, cherished and will deeply miss despite our rejoicing that he is now made perfect and no longer suffers.  Although Roger was born in 1955, he often seemed to be from a far earlier era of extreme modesties and occasional political incorrectness.  The stories will be passed on for many decades.</p>
</div>
</div>

app/views/static_pages/giving.html.erb
<% provide(:title, "Giving") %>
<div class="container stuff">
	<h1 style="font-size: 7rem; font-weight: bold;">Giving</h1>

	<div class="card">
		<div class="row gofundme">
			<div class="col-md-4">
				<embed height="382rem;" noscroll="true" id="roger-michael-funeral-campaign" src="//www.gofundme.com/mvc.php?route=widgets/mediawidget&fund=roger-michael-funeral-campaign&image=1&coinfo=1&preview=1&nocache=1" type="text/html"></embed>
			</div>
			<aside class="col-md-8">
				<div class="card card-gofundme">
				    <h3 style="font-size: 6rem; text-align: center;"><strong>GoFundMe</strong></h3>
				    <p>Because the Memorial Services will not be at a funeral home, it may be difficult to arrange for flowers.  In lieu of flowers please consider supporting the family with a donation toward the funeral expenses through a GoFundMe that has been established.</p>
				</div>
		    </aside>
		</div>
	</div>

	<div class="card">
		<div class="row">
			<% if logged_in? %>
				<div class="col-md-7">
			<% else %>
				<div class="col">
			<% end %>
					<h1>Instructions for Food gifts</h1>

					<p>You may also choose to support the family by bringing food to share following the Fort Wayne Memorial Service.  Please make a post on the Giving page with a brief mention of what you will be bringing just so everyone has an idea of what might be needed.  The family thanks you for your words and acts of sympathy and support.</p>

					<p style="margin-top: 2vh;"></p>
				</div>
				<% if logged_in? %>
				<aside class="col-md-5">
				    <section class="user_info">
				    	<%= render 'shared/user_info' %>
				    </section>
				    <section class="giving_form">
				    	<%= render 'shared/giving_form' %>
				    </section>
			    </aside>
			<% end %>
		</div>
	</div>

	<div class="card">
		<h3>Current list:</h3>
		<%= render 'shared/gifts' %>
	</div>
</div>

app/views/static_pages/home.html.erb
<div class="parallax"></div>

<div class="memoriam" id="memoriam">
	<h1>Roger Mark Michael</h1>
	<br>
	<h3>July 1, 1955 - Jan. 5, 2019</h3>
	<%= link_to "Sign up now!", signup_path, class: "btn btn-lg btn-primary outline" %>
	<div class="scroll-rules">
		<hr class="medium">
		<hr class="long">
		<hr class="short">
	</div>
	<h3>Scroll for more</h3>
	<a href="#wheat"><i class="fas fa-caret-down"></i></a>
</div>

<div class="wheat" id="wheat"></div>

<div class="container home" id="content">

	<div class="row mb-2">
		<div class="col-md-6">
			<div class="card flex-md-row mb-4">
				<div class="card-body">
					<div class="card-text">
						<h3 class="card-title"><strong>Share Your Memories</strong></h3>
						<p class="card-text">Sign up with your e-mail and post your thoughts, memories, and photos with the rest of Roger's family and friends.</p>
					</div>
					<p class="card-link">
						<%= link_to "Make a post", share_path %>
					</p>
				</div>
			</div>
		</div>

		<div class="col-md-6">
			<div class="card flex-md-row mb-4">
				<div class="card-body">
					<div class="card-text">
						<h3 class="card-title"><strong>Find Service Information</strong></h3>
						<p class="card-text">There will be two services. One in West Virginia and one in Fort Wayne. Follow the link below to learn more.</p>
					</div>
					<p class="card-link">
						<%= link_to "Click for more", information_path %>
					</p>
				</div>
			</div>
		</div>
	</div>

	<div class="card">
		<div class="row">
			<div class="col-md-4 gofundme">
				<embed height="382rem;" noscroll="true" id="roger-michael-funeral-campaign" src="//www.gofundme.com/mvc.php?route=widgets/mediawidget&fund=roger-michael-funeral-campaign&image=1&coinfo=1&preview=1&nocache=1" type="text/html"></embed>
			</div>
			<div class="card col-md-8">
				<div>
					<h3 class="card-title"><strong>Support</strong></h3>
					<p>Because the Memorial Services will not be at a funeral home, it may be difficult to arrange for flowers.  In lieu of flowers please consider supporting the family with a donation toward the funeral expenses through a GoFundMe campaign set up by the family.</p>
					<p class="card-link">
						<%= link_to "Learn more", giving_path %>
					</p>
				</div>
			</div>
		</div>
	</div>

	<div class="card">
		<div class="row">
			<div class="col-md-5 home-bio-img">
				<div class="card-img"></div>
			</div>
			<div class="col-md-7">
					<h1>Biography</h1>

					<p><strong>ROGER MARK MICHAEL</strong>, 63, departed this life for the next on January 5, 2019.  Born on July 1, 1955, in Clarksburg WV to Ernest and Martha Michael, and he was a graduate of South Harrison High School.  Roger resided in Fort Wayne IN with his wife of 25 years...</p>

					<br>

					<p class="card-link"><%= link_to "Continue reading", bio_path %></p>
			</div>
		</div>
	</div>
</div>

app/views/static_pages/information.html.erb
<% provide(:title, "Service Information") %>
<div class="container stuff">
<h1>Service Information</h1>

<div class="wv jumbotron p-3 p-md-5 text-white rounded bg-dark col-md-5 col-sm-12">

	<h1>West Virginia</h1>

	<dl class="row">
		<dt class="col-sm-3">Date:</dt>
		<dd class="col-sm-9">Saturday, January 12th at 1:00 pm</dd>
		<br><br>
		<dt class="col-sm-3">Venue:</dt>
		<dd class="col-sm-9">Horizons Church</dd>
		<br><br>
		<dt class="col-sm-3">Address:</dt>
		<dd class="col-sm-9">
			<u>8302 Mount Clare Road
			<br>
			Lost Creek, WV 26385</u>
		</dd>
	</dl>
</div>

<div class="fw jumbotron p-3 p-md-5 text-white rounded bg-dark col-md-5 col-sm-12">

	<h1>Indiana</h1>

	<dl class="row">
		<dt class="col-sm-3">Date:</dt>
		<dd class="col-sm-9">Saturday, January 19th at 11:00am</dd>
		<br><br>
		<dt class="col-sm-3">Venue:</dt>
		<dd class="col-sm-9">Salomon Farm Park Learning Center</dd>
		<br><br>
		<dt class="col-sm-3">Address:</dt>
		<dd class="col-sm-9">
			<u>817 West Dupont Road
			<br>
			Fort Wayne, IN 46825</u>
		</dd>
	</dl>

	<p>Immediately following the service there will be a time of food and fellowship.</p>
</div>
</div>

app/views/static_pages/share.html.erb
<% provide(:title, "Share") %>
<div class="container stuff">
<h1>Share your memories and photos</h1>

<% if logged_in? %>
	<div class="card">
			<aside>
			    <section class="user_info">
			    	<%= render 'shared/user_info' %>
			    </section>
			    <section class="giving_form">
			    	<%= render 'shared/micropost_form' %>
			    </section>
		    </aside>
	</div>
<% end %>

<div class="card">
	<div class="row">
		<aside>
			<h1>Memory Feed</h1>
			<%= render 'shared/feed' %>
		</aside>
	</div>
</div>
</div>