config/routes.rb
Rails.application.routes.draw do
	root   'static_pages#home'
	get    '/share',   to: 'static_pages#share'
	get    '/information', to: 'static_pages#information'
	get    '/bio',   to: 'static_pages#bio'
	get    '/giving', to: 'static_pages#giving'
	get    '/signup',  to: 'users#new'
	post   '/signup',  to: 'users#create'
	get    '/login',   to: 'sessions#new'
	post   '/login',   to: 'sessions#create'
	delete '/logout',  to: 'sessions#destroy'
	resources :users do
	    member do
	    	get :following, :followers
	    end
	end
	resources :microposts,          only: [:create, :destroy]
	resources :foods,          only: [:create, :destroy]
	resources :relationships,       only: [:create, :destroy]
	# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_footer.html.erb
<footer class="footer">
	<small>
		West Virginia -> Washington D.C. -> Fort Wayne, IN
	</small>
	<nav>
		<ul>
			<li>Created by Dakota Michael</li>
		</ul>
	</nav>
</footer>

app/views/layouts/_header.html.erb
<header>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark" id="navbar">
  	<%= link_to "Roger Michael | In Memoriam", root_path, class: "navbar-brand" %>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
  		<ul class="navbar-nav">
  			<li class="nav-item active"><%= link_to "Home", root_path,  class: "nav-link" %></li>
        <li class="nav-item"><%= link_to "Bio", bio_path, class: "nav-link" %></li>
        <li class="nav-item"><%= link_to "Share", share_path, class: "nav-link" %></li>
        <li class="nav-item"><%= link_to "Service Info",  information_path, class: "nav-link" %></li>
        <li class="nav-item"><%= link_to "Giving", giving_path, class: "nav-link" %></li>
        <% if logged_in? %>
            <li class="nav-item"><%= link_to "Users", users_path, class: "nav-link" %></li>
        <% end %>
          <% if logged_in? %>
              <li class="nav-item dropdown">
                  <a href="#" class="nav-link dropdown-toggle" id="navbarDropdownMenuLink" data-toggle="dropdown">
                      Account
                  </a>
                  <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                      <%= link_to "Profile", current_user, class:"dropdown-item" %>
                      <%= link_to "Settings", edit_user_path(current_user), class:"dropdown-item" %>
                      <%= link_to "Log out", logout_path, method: :delete, class:"dropdown-item" %>
                  </div>
              </li>
          <% else %>
    		    <li class="nav-item"><%= link_to "Log In", login_path, class:"nav-link" %></li>
          <% end %>
  		</ul>
  	</nav>
</header>

app/views/layouts/_rails_default.html.erb
<%= csrf_meta_tags %>
<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>

<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

app/views/layouts/_shim.html.erb
<!--[if lt IE9]>
	<script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js"
	</script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= render 'layouts/rails_default' %>
    <%= render 'layouts/shim' %>
    <script defer src="https://use.fontawesome.com/releases/v5.6.3/js/all.js" integrity="sha384-EIHISlAOj4zgYieurP0SdoiBYfGJKkgWedPHH4jCzpCXLmzVsw1ouK59MuUtP4a1" crossorigin="anonymous"></script>
  </head>
  <body class="<%= controller_name %> <%= action_name %>">
    <main role="main">
    <%= render 'layouts/header' %>
      <% flash.each do |message_type, message| %>
       <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
        <% end %>
    	 <%= yield %>
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
    </main>
  </body>
</html>